services:
  seanime:
    image: valgul/seanime:latest
    container_name: seanime-container
    depends_on:
      - torrent
    volumes:
      - ./downloads:/downloads
      - ./config:/root/.config/Seanime
        #- /usr/lib/x86_64-linux-gnu/dri/:/usr/lib/x86_64-linux-gnu/dri/ # uncomment for intel support
        #devices: # uncomment for intel support
        #      - /dev/dri/card0:/dev/dri/card0 # uncomment for intel support
        #      - /dev/dri/renderD128:/dev/dri/renderD128 # uncomment for intel support
        #    group_add: # uncomment for intel support
        #      - "video" # uncomment for intel support
        #      - 105 # uncomment for intel support
    ports: 
      - 43210:43211
        #network_mode: "service:gluetun" # uncomment if using gluetun also comment all ports section
    #deploy: # nvidia and you need NVIDIA Container Toolkit
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: torrent
    environment:
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./appdata:/config
      - ./downloads:/downloads # same as seanime downloads folder
    ports:
      - 43212:8080
      - 43213:6881
      - 43213:6881/udp
    restart: unless-stopped
    #network_mode: "service:gluetun" # uncomment if using gluetun also comment all ports section

  #gluetun: #so your torrent use a vpn (would be bad if it was your ip)
    #image: qmcgaw/gluetun
    #container_name: gluetun
    #cap_add:
      #- NET_ADMIN
    #devices:
      #- /dev/net/tun:/dev/net/tun
    #ports:
      #- 8888:8888/tcp # HTTP proxy
      #- 8388:8388/tcp # Shadowsocks
      #- 8388:8388/udp # Shadowsocks

      #- 8080:8080 #torrent
      #- 6881:6881 #torrent
      #- 6881:6881/udp #torrent
    #environment:
      #- FIREWALL_INPUT_PORTS=8080,6881,43211
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      #- VPN_SERVICE_PROVIDER=
